version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ github.token }}
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}
updates:
  - package-ecosystem: 'npm'
    registries:
      - npm-github
      - npm-npmjs
    directory: '/'
    registries:
    - npm-github
    schedule:
      interval: 'weekly'
    assignees:
      - 'tjsr'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    assignees:
      - 'tjsr'
